config/routes.rb
Omrails::Application.routes.draw do

  get "users/show"

  get "user/show"

  resources :pins

  devise_for :users
  match 'users/:id' => 'users#show', as: :user

  root :to => 'pins#index'
  get 'about' => 'pages#about'

  match '/terms' => 'pages#terms'
  match '/privacy' => 'pages#privacy'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :image_remote_url

  validates :description, presence: true
	validates :user_id, presence: true
	validates_attachment :image, presence: true,
												content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
												size: { less_than: 5.megabytes }

  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240" }

  def image_remote_url=(url_value)
  	self.image = URI.parse(url_value) unless url_value.blank?
  	super
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :pins, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
      format.js
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = Pin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @pins = @user.pins.page(params[:page]).per_page(20)
   	respond_to do |format|
   		format.html # show.html.erb
      format.json { render json: @user }
			format.js
		end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to image_tag("/images/YIN_tag.png", :alt => "Your Inspiration Network"), root_path, class: "brand" %>
		by <%= link_to "Rasheed Bustamam", "http://www.Blog2Success.net" %>
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to image_tag("/images/YIN_tag.png", :alt => "Your Inspiration Network"), root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <ul class="nav">
	        <li>
	        	<%= link_to "Home", root_path %>
	        </li>
			    <li>
				    <%= link_to "About", about_path %>
			    </li>
          <li>
            <%= link_to "Terms", terms_path %>
          </li>
          <li>
            <%= link_to "Privacy", privacy_path %>
          </li>
		    </ul>
		    <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to "Add +", new_pin_path %>
            </li>
            <li>
              <%= link_to "Edit Profile", edit_user_registration_path %>
            </li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to "Login", new_user_session_path %>
	          </li>
          <% end %>
		    </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= @title %></title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<%= render 'layouts/header' %>

		<div class="container">
      <% flash.each do |name, msg| %>
      	<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      	<% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
		</div>

	</body>
</html>

app/views/pages/_home.html.erb
<% @title ="Your Inspirational Network" %>
<% unless user_signed_in? %>
	<div class="hero-unit">
    <center><h1>Welcome to</h1>
    <br>
    <img src="/images/YIN_logo.png">
    <br>
    <p>
        Inspirational photos. Without all the fluff.
    </p>
	<p> 
        <%= link_to 'Sign up now!', new_user_registration_path, class: "btn btn-large btn-primary" %> 
    </p>
    </center>
	</div>
<% end %>

app/views/pages/about.html.erb
<% @title ="About" %>
<h1>About</h1>
<p>
  <%= link_to "Your Inspiration Network", root_path %>
  is a social network designed to  
  inspire, encourage, and motivate its users.
</p>

<%= link_to 'Sign up now!', new_user_registration_path, class: "btn btn-large btn-primary" %> 

app/views/pages/home.html.erb
<div class="center hero-unit">
    <h1>Welcome to One Month Rails! </h1>
    <p>
    	You've found the home page for the 
    	<%= link_to 'One Month Rails',  "http://onemonthrails.com" %>
    	application.
     </p>

    <p> 
    	<%= link_to 'Sign up now!', new_user_registration_path, class: "btn btn-large btn-primary" %> 
    </p>
</div>

app/views/pages/privacy.html.erb
<% @title ="Privacy Policy" %>
<h1>Privacy Policy</h1>
<!-- START PRIVACY POLICY CODE -->
<div style="font-family:arial">
<strong>What information do we collect?</strong> 
<br />
<br />We collect information from you when you register on our site or fill out a form.  
<br />
<br />When ordering or registering on our site, as appropriate, you may be asked to enter your: name or e-mail address. You may, however, visit our site anonymously.
<br />
<br />
<strong>What do we use your information for?</strong> 
<br />
<br />Any of the information we collect from you may be used in one of the following ways: 
<ul>
<li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
<li>To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you) </li>
<li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
<li>To administer a contest, promotion, survey or other site feature</li>
<li>To send periodic emails</li>
</ul>
<blockquote>The email address you provide for order processing, may be used to send you information and updates pertaining to your order, in addition to receiving occasional company news, updates, related product or service information, etc.</blockquote>
Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.
<br />
<br />
<br />
<br />
<strong>How do we protect your information?</strong> 
<br />
<br />We implement a variety of security measures to maintain the safety of your personal information when you enter, submit, or access your personal information. 
<br /> 
<br />We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to?keep the information confidential.
<br />
<br />After a transaction, your private information (credit cards, social security numbers, financials, etc.) will not be stored on our servers.
<br />
<br />
<strong>Do we use cookies?</strong> 
<br />
<br />Yes (Cookies are small files that a site or its service provider transfers to your computers hard drive through your Web browser (if you allow) that enables the sites or service providers systems to recognize your browser and capture and remember certain information
<br />
<br /> We use cookies to understand and save your preferences for future visits and compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.
<br />
<br />
<strong>Do we disclose any information to outside parties?</strong> 
<br />
<br />We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.
<br />
<br />
<strong>Third party links</strong> 
<br />
<br /> Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.
<br />
<br />
<strong>California Online Privacy Protection Act Compliance</strong>
<br />
<br />Because we value your privacy we have taken the necessary precautions to be in compliance with the California Online Privacy Protection Act. We therefore will not distribute your personal information to outside parties without your consent.
<br />
<br />As part of the California Online Privacy Protection Act, all users of our site may make any changes to their information at anytime by logging into their control panel and going to the 'Edit Profile' page.
<br />
<br />
<strong>Childrens Online Privacy Protection Act Compliance</strong> 
<br />
<br />We are in compliance with the requirements of COPPA (Childrens Online Privacy Protection Act), we do not collect any information from anyone under 13 years of age. Our website, products and services are all directed to people who are at least 13 years old or older.
<br />
<br />
<strong>Online Privacy Policy Only</strong> 
<br />
<br />This online privacy policy applies only to information collected through our website and not to information collected offline.
<br />
<br />
<strong>Your Consent</strong> 
<br />
<br />By using our site, you consent to our web site privacy policy.
<br />
<br />
<strong>Changes to our Privacy Policy</strong> 
<br />
<br />If we decide to change our privacy policy, we will post those changes on this page, send an email notifying you of any changes, and/or update the Privacy Policy modification date below.
<br />
<br />This policy was last modified on 05 April 2013.

app/views/pages/terms.html.erb
<% @title ="Terms and Conditions" %>
<h1>Terms and Conditions</h1>
<p>
  <p>This web page represents a legal document that serves as our Terms of Service and it governs the legal terms of our website, http://serene-ocean-1479.herokuapp.com, sub-domains, and any associated web-based and mobile applications (collectively, "Website"), as owned and operated by Your Inspire Network.</p>    
<p>Capitalized terms, unless otherwise defined, have the meaning specified within the Definitions section below. This Terms of Service, along with our Privacy Policy, any mobile license agreement, and other posted guidelines within our Website, collectively "Legal Terms", constitute the entire and only agreement between you and Your Inspire Network, and supersede all other agreements, representations, warranties and understandings with respect to our Website and the subject matter contained herein. We may amend our Legal Terms at any time without specific notice to you. The latest copies of our Legal Terms will be posted on our Website, and you should review all Legal Terms prior to using our Website. After any revisions to our Legal Terms are posted, you agree to be bound to any such changes to them. Therefore, it is important for you to periodically review our Legal Terms to make sure you still agree to them.</p>
<p>By using our Website, you agree to fully comply with and be bound by our Legal Terms. Please review them carefully. If you do not accept our Legal Terms, do not access and use our Website. If you have already accessed our Website and do not accept our Legal Terms, you should immediately discontinue use of our Website.</p>
<p>The last update to our Terms of Service was posted on April 6, 2013.</p>

<p><strong>Definitions</strong><br />The terms "us" or "we" or "our" refers to Your Inspire Network, the owner of the Website.</p>
<p>A "Visitor" is someone who merely browses our Website, but has not registered as Member.</p>
<p>A "Member" is an individual that has registered with us to use our Service.</p>
<p>Our "Service" represents the collective functionality and features as offered through our Website to our Members.</p>
<p>A "User" is a collective identifier that refers to either a Visitor or a Member.</p>
<p>All text, information, graphics, audio, video, and data offered through our Website are collectively known as our "Content".</p>

<p><strong>Legal Compliance</strong><br />You agree to comply with all applicable domestic and international laws, statutes, ordinances, and regulations regarding your use of our Website. Your Inspire Network reserves the right to investigate complaints or reported violations of our Legal Terms and to take any action we deem appropriate, including but not limited to canceling your Member account, reporting any suspected unlawful activity to law enforcement officials, regulators, or other third parties and disclosing any information necessary or appropriate to such persons or entities relating to your profile, email addresses, usage history, posted materials, IP addresses and traffic information, as allowed under our Privacy Policy.</p>

<p><strong>Intellectual Property</strong><br />Our Website may contain our service marks or trademarks as well as those of our affiliates or other companies, in the form of words, graphics, and logos. Your use of our Website does not constitute any right or license for you to use such service marks/trademarks, without the prior written permission of the corresponding service mark/trademark owner. Our Website is also protected under international copyright laws. The copying, redistribution, use or publication by you of any portion of our Website is strictly prohibited. Your use of our Website does not grant you ownership rights of any kind in our Website.</p>

<p><strong>Links to Other Websites</strong><br />Our Website may contain links to third party websites. These links are provided solely as a convenience to you. By linking to these websites, we do not create or have an affiliation with, or sponsor such third party websites. The inclusion of links within our Website does not constitute any endorsement, guarantee, warranty, or recommendation of such third party websites. Your Inspire Network has no control over the legal documents and privacy practices of third party websites; as such, you access any such third party websites at your own risk.</p>

<p><strong>General Terms</strong><br />Our Legal Terms shall be treated as though it were executed and performed in California, United States, and shall be governed by and construed in accordance with the laws of California, United States, without regard to conflict of law principles. In addition, you agree to submit to the personal jurisdiction and venue of such courts. Any cause of action by you with respect to our Website, must be instituted within one (1) year after the cause of action arose or be forever waived and barred. Should any part of our Legal Terms be held invalid or unenforceable, that portion shall be construed consistent with applicable law and the remaining portions shall remain in full force and effect. To the extent that any Content in our Website conflicts or is inconsistent with our Legal Terms, our Legal Terms shall take precedence. Our failure to enforce any provision of our Legal Terms shall not be deemed a waiver of such provision nor of the right to enforce such provision. The rights of Your Inspire Network under our Legal Terms shall survive the termination of our Legal Terms.</p>

<p>Published with permission from <a href="http://termsfeed.com" title="TermsFeed">TermsFeed</a>.</p>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

	<%= f.input :image, label: "Upload an image" %>
	<%= f.input :image_remote_url, label: "or enter a URL" %>
  <%= f.input :description, as: :text, input_html: { rows: "3" } %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<% @title ="Pins" %>
<div class="box">
  <%= link_to (image_tag pin.image(:medium)), pin %>
  <p class="description">
		<%= pin.description %>
	</p>
	<p>
		<strong>
      Posted by <%= link_to pin.user.name, pin.user %>
    </strong>
	</p>
 	<% if current_user == pin.user %>
		<p>
			<%= link_to 'Edit', edit_pin_path(pin) %>
			<%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
		</p>
	<% end %>
</div>

app/views/pins/edit.html.erb
<% @title ="Edit Pin" %>
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<% @title ="Your Inspiration Network" %>
<%= render 'pages/home' %>

<div id="pins">
  <%= render @pins %>
</div>

<%= will_paginate @pins %>

app/views/pins/index.js.erb
$boxes = $('<%= j render( @pins ) %>')

 $('#pins').append( $boxes ).imagesLoaded( function(){ 
 $('#pins').masonry( 'reload'); 
});
<% if  @pins .next_page %>
  $('.pagination').replaceWith('<%= j will_paginate( @pins ) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/pins/new.html.erb
<% @title ="New Pin" %>
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<% @title ="Pins" %>
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @pin.image %>
			<p>
			  <%= @pin.description %>
			</p>
			<p>
			  <%= @pin.user.name %>
			</p>
			<% if current_user == @pin.user %>
				<%= link_to 'Edit', edit_pin_path(@pin) %> |
			<% end %>
			<%= link_to 'Back', pins_path %>		
		</div>
	</div>
</div>

app/views/pins/show.js.erb
$boxes = $('<%= j render( @pins ) %>')

 $(#pins).append( $boxes ).imagesLoaded( function(){ 
 $(#pins).masonry( reload); 
});
<% if  @pins .next_page %>
  $('.pagination').replaceWith('<%= j will_paginate( @pins ) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/users/show.html.erb
<% @title =@user .name %>
<h1><%=  @user .name %>'s Pins</h1>

<div id="pins">
  <%= render  @pins  %>
</div>

<%= will_paginate  @pins  %>

app/views/users/show.js.erb
$boxes = $('<%= j render( @pins ) %>')

 $('#pins').append( $boxes ).imagesLoaded( function(){ 
 $('#pins').masonry( 'reload'); 
});
<% if  @pins .next_page %>
  $('.pagination').replaceWith('<%= j will_paginate( @pins ) %>');
<% else %>
  $('.pagination').remove();
<% end %>